diary/diary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts'))
]

diary/posts/urls.py
from django.urls import path
from . import views


app_name='posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>', views.group_list, name='group_list'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('posts/<int:post_id>', views.post_detail, name='post_detail'),
]

diary/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path(
        'logout',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'signup/',
        views.SignUp.as_view(), name='signup'
    )
]

diary/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    '''Создает группу.'''
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):
        return self.title[:15]


class Post(models.Model):
    '''Создаёт объект поста.'''
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts'
    )
    count = models.IntegerField(
        default=0
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

diary/users/models.py
from django.db import models

# Create your models here.

diary/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    '''Создаёт форму для нового поста.'''
    class Meta:
        model = Post

        fields = ('text', 'group')

diary/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    '''Создает форму нового пользователя.'''
    class Meta(UserCreationForm.Meta):
        model = User

        fields = ('first_name', 'last_name', 'username', 'email')

diary/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Post, User, Group
from .utils import paginator


def index(request):
    '''Выводит последние добавленные посты.'''
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = paginator(request, posts)

    context = {
        'page_obj': page_obj
    }

    return render(request, template, context)


def group_list(request, slug):
    '''Выводит посты принадлежащие только данной группе.'''
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator(request, posts)

    context = {
       'page_obj': page_obj 
    }

    return render(request, template, context)


def profile(request, username):
    '''Выводит посты пользователя.'''
    template = 'posts/profile.html'

    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator(request, posts)

    context = {
        'page_obj': page_obj,
        'author': author
    }

    return render(request, template, context)


def post_detail(request, post_id):
    '''Выводит детали поста.'''
    template = 'posts/post_detail.html'
    post = Post.objects.get(id=post_id)
    user = post.author
    posts_num = user.posts.count()

    Post.objects.filter(id=post_id).update(count=post.count + 1)

    context = {
        'post': post,
        'posts_num': posts_num
    }

    return render(request, template, context)

diary/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

diary/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружает фреймворк bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <!-- Загружает иконки для различных устройств -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/book.png' %}">
    <link rel="icon" type="image/png" size="16x16" href="{% static 'img/book.png' %}">
    <!-- Задаёт цвет фона плитки -->
    <meta name="msapplication-TileColor" content="#000"> 
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли!!!
      {% endblock %}
    </maim>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

diary/templates/includes/footer.html
<div class="border-top text-center py-3">
  <p>© 2022 Copyright</p>
</div>

diary/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/book.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span>Diary</span>
    </a>
  </div>
</nav>

diary/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="item-page">
        <a class="item-link" href="?page={{ page_obj.previous_page_number }}">
          &lt; &bull;
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="item-page">
          <span class="item-link active">{{ i }}</span>
        </li>
      {% else %}
        <li class="item-page">
          <a class="item-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="item-page">
        <a class="item-link" href="?page={{ page_obj.next_page_number }}">
          &bull; &gt;
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

diary/templates/includes/post.html
{% load static %}
<div class="container posts_wall">
  <div class="post">
    {{ post.text }}
    <hr>
    <div class="label">
      <span><img src="{% static 'img/eye.png' %}" width="20" height="20"></span>
      <span>{{ post.count }}</span>
    </div>
    <div class="row label">
      <div class="col-12 col-md-9">
        <a href="{% url 'posts:profile' post.author.username %}" class="relation">
          {{ post.author.first_name }} {{ post.author.last_name }} |
        </a>
        <span>{{ post.pub_date|date:"d E Y" }} года</span>
      </div>
      {% if post.group %}
        <div class="col-12 col-md-3">
          <a href="{% url 'posts:group_list' post.group.slug %}" class="relation">
            {{ post.group.title }}
          </a>
          |
          <a href="{% url 'posts:post_detail' post.id %}" class="relation">
            Подробнее...
          </a>
        </div>
      {% else %}
        <div class="col-12 col-md-3">
          ********
          |
          <a href="{% url 'posts:post_detail' post.id %}" class="relation">
            Подробнее...
          </a>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% if forloop.last %}
  <hr>
{% endif %}

diary/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
  {% endfor %}
  <div class="container">
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

diary/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
  {% endfor %}
  <div class="container">
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

diary/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block content %}
  <div class="container py-5 desk_post">
    <div class="row">
      <div class="col-12 col-lg-4 description">
        <ul>
          <li>Автор поста: 
            <a href="{% url 'posts:profile' post.author.username %}"
              <span class="data">
                {{ post.author.first_name }}
                {{ post.author.last_name }}
              </span>
            </a>
          </li>
          <li>Всего постов пользователя:
            <span class="data">
              {{ posts_num }}
            </span>
          </li>
          <li>
            Группа:
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                <span class="data">{{ post.group.title }}</span>
              </a>
            {% else %}
              <span class="data">*******</span>
            {% endif %}
          </li>
          <li>
            Количество просмотров:
            <span class="data">{{ post.count }}</span>
          </li>
        </ul>
      </div>
      <div class="col-8">
        {{ post.text }}
      </div>
    </div>
  </div>
{% endblock %}

diary/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Страница профайла {{ author.username }}{% endblock %}
{% block content %}
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
  {% endfor %}
  <div class="container">
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

diary/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём Вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

diary/templates/users/signup.html
{% extends 'base.html' %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
  </div>
{% endblock %}